
name: MY-services-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


    
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb
        ports:
          - 3306
        volumes:
        - ${{ github.workspace }}/projarka/table-sql:/docker-entrypoint-initdb.d
        env:
          MYSQL_ROOT_PASSWORD: rootdb
          MYSQL_DATABASE: projarka
          MYSQL_USER: user
          MYSQL_PASSWORD: user
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: my python test
        run: |
          cd services
          sleep 5
          python3 api.py &
          sleep 5
          curl localhost:8888
      - name: Test 1
        run: |
          echo Some Text